// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Location used to resolve a selected capability root.
 */
export type CapabilityRootLocation = { "type": "environment", environmentId: string, path: string, };
