// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigReadParams = { includeLayers?: boolean,
/**
 * Optional working directory to resolve project config layers. If specified,
 * return the effective config as seen from that directory (i.e., including any
 * project layers between `cwd` and the project/repo root).
 */
cwd?: string | null, };
