// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionProfileListParams = {
/**
 * Opaque pagination cursor returned by a previous call.
 */
cursor?: string | null,
/**
 * Optional page size; defaults to the full result set.
 */
limit?: number | null,
/**
 * Optional working directory to resolve project config layers.
 */
cwd?: string | null, };
