// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PermissionProfileSummary = {
/**
 * Available permission profile identifier.
 */
id: string,
/**
 * Optional user-facing description for display in clients.
 */
description: string | null, };
