// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

export type PluginInstalledParams = {
/**
 * Optional working directories used to discover repo marketplaces.
 */
cwds?: Array<AbsolutePathBuf> | null,
/**
 * Additional uninstalled plugin names that should be returned when present locally.
 * This is used by mention surfaces that intentionally expose install entrypoints.
 */
installSuggestionPluginNames?: Array<string> | null, };
