// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityRootLocation } from "./CapabilityRootLocation";

/**
 * A user-selected root that can expose one or more runtime capabilities.
 */
export type SelectedCapabilityRoot = {
/**
 * Stable identifier supplied by the capability selection platform.
 */
id: string,
/**
 * Where the selected root can be resolved.
 */
location: CapabilityRootLocation, };
