// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SortDirection } from "./SortDirection";
import type { TurnItemsView } from "./TurnItemsView";

export type ThreadResumeInitialTurnsPageParams = {
/**
 * Optional turn page size.
 */
limit?: number | null,
/**
 * Optional turn pagination direction; defaults to descending.
 */
sortDirection?: SortDirection | null,
/**
 * How much item detail to include for each returned turn; defaults to summary.
 */
itemsView?: TurnItemsView | null, };
