// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

export type TurnsPage = { data: Array<Turn>, nextCursor: string | null, backwardsCursor: string | null, };
