/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConfigBundleResponse {
    #[serde(
        rename = "config_toml",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub config_toml: Option<Option<Box<models::DeliveredConfigToml>>>,
    #[serde(
        rename = "requirements_toml",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub requirements_toml: Option<Option<Box<models::DeliveredRequirementsToml>>>,
}

impl ConfigBundleResponse {
    pub fn new() -> ConfigBundleResponse {
        ConfigBundleResponse {
            config_toml: None,
            requirements_toml: None,
        }
    }
}
