/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveredConfigToml {
    #[serde(
        rename = "enterprise_managed",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub enterprise_managed: Option<Option<Vec<models::DeliveredTomlFragment>>>,
}

impl DeliveredConfigToml {
    pub fn new() -> DeliveredConfigToml {
        DeliveredConfigToml {
            enterprise_managed: None,
        }
    }
}
