/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveredTomlFragment {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "contents")]
    pub contents: String,
}

impl DeliveredTomlFragment {
    pub fn new(id: String, name: String, contents: String) -> DeliveredTomlFragment {
        DeliveredTomlFragment { id, name, contents }
    }
}
