/*
 * codex-backend
 *
 * codex-backend
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpendControlStatusDetails {
    #[serde(rename = "reached")]
    pub reached: bool,
    #[serde(
        rename = "individual_limit",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub individual_limit: Option<Option<Box<models::SpendControlLimitDetails>>>,
}

impl SpendControlStatusDetails {
    pub fn new(reached: bool) -> SpendControlStatusDetails {
        SpendControlStatusDetails {
            reached,
            individual_limit: None,
        }
    }
}
