// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects which part of the active context is charged against
 * `model_auto_compact_token_limit`.
 */
export type AutoCompactTokenLimitScope = "total" | "body_after_prefix";
